// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/AboutUs.tsx";
import * as $$$$$$1 from "./sections/Accordion.tsx";
import * as $$$$$$2 from "./sections/BannerText.tsx";
import * as $$$$$$3 from "./sections/Benefits.tsx";
import * as $$$$$$4 from "./sections/CustomText.tsx";
import * as $$$$$$5 from "./sections/Footer.tsx";
import * as $$$$$$6 from "./sections/Hero.tsx";
import * as $$$$$$7 from "./sections/ItWorks.tsx";
import * as $$$$$$8 from "./sections/Partners.tsx";
import * as $$$$$$9 from "./sections/Prices.tsx";
import * as $$$$$$10 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/AboutUs.tsx": $$$$$$0,
    "site/sections/Accordion.tsx": $$$$$$1,
    "site/sections/BannerText.tsx": $$$$$$2,
    "site/sections/Benefits.tsx": $$$$$$3,
    "site/sections/CustomText.tsx": $$$$$$4,
    "site/sections/Footer.tsx": $$$$$$5,
    "site/sections/Hero.tsx": $$$$$$6,
    "site/sections/ItWorks.tsx": $$$$$$7,
    "site/sections/Partners.tsx": $$$$$$8,
    "site/sections/Prices.tsx": $$$$$$9,
    "site/sections/Theme/Theme.tsx": $$$$$$10,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
